services:
  - type: web
    name: rpm-auto-dealership
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rpm-auto-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: rpm-auto-db
    databaseName: rpm_auto
    plan: starter